services:
  - type: web
    name: online-exam-system
    runtime: python
    buildCommand: "pip install -r requirements.txt && python db_setup.py && python seed_data.py"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
